FROM node:12-alpine
WORKDIR /wh-tickets-api
COPY package.json yarn.lock ./
COPY migrations migrations
COPY database.json database.json
RUN ["npm install"]

CMD ["./node_modules/.bin/db-migrate", "up"]