DROP TABLE tickets;
DROP TABLE group_permissions;
DROP TABLE user_authentications;
DROP TABLE user_groups;
DROP TABLE permissions;
DROP TABLE users;
DROP TABLE groups;
DROP TABLE organizations;
DROP TABLE authenticators;