

--    -- --------------------------------------------------------
--    -- U S E R   A U T H E N T I C A T I O N S
--    --
--    INSERT INTO user_authentications (
--        user_id,
--        authentication_id,
--        authenticator_id,
--
--        creation_date,
--        creation_user_id
--    )
--    VALUES
--    (
--        customer1_user_id,
--        'auth0|5ebb3139dc1d2b0c033355fe',
--        auth0_authenticator_id,
--
--        now(),
--        system_user_id
--    ),
--    (
--        customer2_user_id,
--        'auth0|5ebe419ca361c20c74a951fa',
--        auth0_authenticator_id,
--
--        now(),
--        system_user_id
--    ),
--    (
--        employee1_user_id,
--        'auth0|5ebb314f62bd5e0c701ac502',
--        auth0_authenticator_id,
--
--        now(),
--        system_user_id
--    ),
--    (
--        manager1_user_id,
--        'auth0|5ebb3165dc1d2b0c033356bf',
--        auth0_authenticator_id,
--
--        now(),
--        system_user_id
--    );
--

