
--    -- --------------------------------------------------------
--    -- G R O U P   P E R M I S S I O N S
--    --
--   INSERT INTO group_permissions (
--        group_id,
--        permission_id,
--
--        creation_date,
--        creation_user_id
--    ) VALUES (
--        employee_group_id,
--        tickets_display_all_permission_id,
--
--        now(),
--        system_user_id
--    ),
--    (
--        employee_group_id,
--        organizations_display_all_permission_id,
--
--        now(),
--        system_user_id
--    ),
--    (
--        manager_group_id,
--        tickets_display_all_permission_id,
--
--        now(),
--        system_user_id
--    ),
--    (
--        manager_group_id,
--        organizations_display_all_permission_id,
--
--        now(),
--        system_user_id
--    ),
--    (
--        manager_group_id,
--        organizations_create_permission_id,
--        now(),
--        system_user_id
--    );
--
--    -- --------------------------------------------------------
--    -- U S E R   G R O U P S
--    --
--    INSERT INTO user_groups (
--        group_id,
--        user_id,
--
--        creation_date,
--        creation_user_id
--    )
--    VALUES
--    (
--        customer_group_id,
--        customer1_user_id,
--
--        now(),
--        system_user_id
--    ),
--    (
--        customer_group_id,
--        customer2_user_id,
--
--        now(),
--        system_user_id
--    ),
--    (
--        employee_group_id,
--        employee1_user_id,
--
--        now(),
--        system_user_id
--    ),
--    (
--        manager_group_id,
--        manager1_user_id,
--
--        now(),
--        system_user_id
--    );
--
--    -- --------------------------------------------------------
--    -- A U T H E N T I C A T O R S
--    --
--    INSERT INTO authenticators (
--        authenticator_id,
--        name,
--
--        creation_date,
--        creation_user_id,
--        modification_date,
--        modification_user_id
--    )
--    VALUES
--    (
--        auth0_authenticator_id,
--        'auth0',
--
--        now(),
--        system_user_id,
--        now(),
--        system_user_id
--    );
--
--    -- --------------------------------------------------------
--    -- U S E R   A U T H E N T I C A T I O N S
--    --
--    INSERT INTO user_authentications (
--        user_id,
--        authentication_id,
--        authenticator_id,
--
--        creation_date,
--        creation_user_id
--    )
--    VALUES
--    (
--        customer1_user_id,
--        'auth0|5ebb3139dc1d2b0c033355fe',
--        auth0_authenticator_id,
--
--        now(),
--        system_user_id
--    ),
--    (
--        customer2_user_id,
--        'auth0|5ebe419ca361c20c74a951fa',
--        auth0_authenticator_id,
--
--        now(),
--        system_user_id
--    ),
--    (
--        employee1_user_id,
--        'auth0|5ebb314f62bd5e0c701ac502',
--        auth0_authenticator_id,
--
--        now(),
--        system_user_id
--    ),
--    (
--        manager1_user_id,
--        'auth0|5ebb3165dc1d2b0c033356bf',
--        auth0_authenticator_id,
--
--        now(),
--        system_user_id
--    );
--

